<?php

define('ERR_LOGIN_ACCOUNT_BLOCKED'			, 'g1k3CoMmRfmPnjFu5Dc', true);
define('ERR_LOGIN_ACCOUNT_MAIL_NOT_FOUND'	, 'm2dkPx9Q03gPSCtRl9K', true);
define('ERR_LOGIN_ACCOUNT_MAIL_INVALID'		, 'bXKQunjnYs1u33GDYlu', true);
define('ERR_LOGIN_ACCOUNT_PASS_INCORRECT'	, 'S9abAtddU9HbNd0pgJq', true);

define('ERR_PAGE_AUTHENTICATION_ERROR'	, 'DYIGNM3E0wtmqgGrP5G', true);
define('ERR_PAGE_AUTHENTICATION_ERROR_INVALID_PUBLIC_TOKEN'	, '1GGNrsSeQ0bl3ztAD63', true);